version: "3"

services:
  app:
    container_name: library-service
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
        - ./:/app
    command: ["./entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A config worker -l INFO -P eventlet"
    depends_on:
      - app
      - redis
      - db
    restart: on-failure
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - app
      - redis
      - db
    restart: on-failure
    env_file:
      - .env
