# Generated by Django 4.0.4 on 2023-12-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_service', '0002_alter_borrowing_options_alter_borrowing_book_id'),
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowing_service.borrowing'),
        ),
    ]
