# Generated by Django 4.0.4 on 2023-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
